export default {
  KEYS: {
    REGISTERED_CITIES_STORAGE_KEY: 'REGISTERED_CITIES_STORAGE_KEY',
    USER_LOCATION_INFO_STORAGE_KEY: 'USER_LOCATION_INFO_STORAGE_KEY',
    APP_STORAGE_KEY: '@WEATHER_APP',
  },

  VALUES: {
    DEFAULT_CITIES: ['Ottawa, Canada', 'Los Angeles, California'],
  }
};
